# Generated by Django 3.1.7 on 2021-05-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naseem', '0005_auto_20210513_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
