# Generated by Django 3.1.7 on 2021-05-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naseem', '0007_customer_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_category',
            new_name='AddCategory',
        ),
    ]
