# Generated by Django 3.1.7 on 2021-05-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naseem', '0009_auto_20210518_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
