# Generated by Django 3.1.7 on 2021-08-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naseem', '0011_auto_20210604_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=20)),
                ('empname', models.CharField(max_length=200)),
                ('empemail', models.CharField(max_length=200)),
                ('empphone', models.CharField(max_length=222)),
                ('empdate', models.DateField()),
            ],
        ),
    ]
